const languageData = {
    'en': {
        essential: 'Essential',
        functional: 'Functional',
        necessary: 'Necessary',
        session: 'Session',
        persistent: 'Persistent',
        performance: 'Performance',
        analytics: 'Analytics',
        targeting: 'Targeting',
        advertising: 'Advertising',
        legal: 'Legal',
        other: 'Other',
        total_third_party_cookies: 'Total Third Party Cookies',
        third_party_requests: 'Third Party Requests',
        first_party_cookies: 'First Party Cookies',
        cookie_policy_present: 'Cookie Policy Present',
        privacy_policy_present: 'Privacy Policy Present',
        online_app_tool_used: 'Online App Tool Used',
        website_name: 'Website Name',
        date_of_visit: 'Date of Website Visit'
    },

    'eufunded': {
        essential: 'Essential',
        functional: 'Functional',
        necessary: 'Necessary',
        session: 'Session',
        persistent: 'Persistent',
        performance: 'Performance',
        analytics: 'Analytics',
        targeting: 'Targeting',
        advertising: 'Advertising',
        legal: 'Legal',
        other: 'Other',
        total_third_party_cookies: 'Total Third Party Cookies',
        third_party_requests: 'Third Party Requests',
        first_party_cookies: 'First Party Cookies',
        cookie_policy_present: 'Cookie Policy Present',
        privacy_policy_present: 'Privacy Policy Present',
        online_app_tool_used: 'Online App Tool Used',
        website_name: 'Website Name',
        date_of_visit: 'Date of Website Visit'
    },
    'de': {
        essential: 'Essentiell',
        functional: 'Funktionell',
        necessary: 'Notwendig',
        session: 'Sitzung',
        persistent: 'Hartnäckig',
        performance: 'Leistung',
        analytics: 'Analytik',
        targeting: 'Ausrichtung',
        advertising: 'Werbung',
        legal: 'Gesetzlich',
        other: 'Andere',
        total_third_party_cookies: 'Cookies von Drittanbietern insgesamt',
        third_party_requests: 'Anfragen von Drittanbietern',
        first_party_cookies: 'First-Party-Cookies',
        cookie_policy_present: 'Cookie-Richtlinie vorhanden',
        privacy_policy_present: 'Datenschutzerklärung vorhanden',
        online_app_tool_used: 'Verwendetes Online-Tool',
        website_name: 'Website Name',
        date_of_visit: 'Besuchsdatum der Website'

    },
    // Hungarian 
    'hu': {
        essential: 'Alapvető',
        functional: 'Funkcionális',
        necessary: 'Szükséges',
        session: 'Ülés',
        persistent: 'Kitartó',
        performance: 'Teljesítmény',
        analytics: 'Analitika',
        targeting: 'Célzás',
        advertising: 'Hirdető',
        legal: 'Jogi',
        other: 'Egyéb',
        total_third_party_cookies: 'Összes harmadik féltől származó cookie',
        third_party_requests: 'Harmadik fél kérései',
        first_party_cookies: 'Első fél süti',
        cookie_policy_present: 'Cookie-szabályzat jelen van',
        privacy_policy_present: 'Jelenlegi adatvédelmi szabályzat',
        online_app_tool_used: 'Használt online alkalmazáseszköz',
        website_name: 'Weboldal neve',
        date_of_visit: 'Weboldal felkeresésének dátuma'
    },
    // Greek language
    'el': {
        essential: 'Ουσιώδης',
        functional: 'Λειτουργικός',
        necessary: 'Απαραίτητη',
        session: 'Συνεδρία',
        persistent: 'Επίμονος',
        performance: 'Εκτέλεση',
        analytics: 'Analytics',
        targeting: 'Στόχευση',
        advertising: 'Διαφήμιση',
        legal: 'Νομικός',
        other: 'Αλλα',
        total_third_party_cookies: 'Σύνολο cookies τρίτων',
        third_party_requests: 'Αιτήματα τρίτων',
        first_party_cookies: 'Cookies πρώτου μέρους',
        cookie_policy_present: 'Ύπαρξη Πολιτικής cookies',
        privacy_policy_present: 'Ύπαρξη πολιτικής απορρήτου',
        online_app_tool_used: 'Χρησιμοποιήθηκε διαδικτυακό εργαλείο',
        website_name: 'Όνομα Ιστοσελίδας',
        date_of_visit: 'Ημερομηνία επίσκεψης Ιστοσελίδας'
    },
    // Spanish
    'es': {
        essential: 'Básico',
        functional: 'Funcional',
        necessary: 'Necesaria',
        session: 'Sesión',
        persistent: 'Persistente',
        performance: 'Actuación',
        analytics: 'Analítica',
        targeting: 'Orientación',
        advertising: 'Publicidad',
        legal: 'Legal',
        other: 'Otro',
        total_third_party_cookies: 'Total de cookies de terceros',
        third_party_requests: 'Solicitudes de terceros',
        first_party_cookies: 'Galletas de primera fiesta',
        cookie_policy_present: 'Presencia de política de cookies',
        privacy_policy_present: 'Presencia de política de privacidad',
        online_app_tool_used: 'Usada herramienta online',
        website_name: 'Nombre Web',
        date_of_visit: 'Fecha de visita de la web'
    },

    // Polish
    'pl': {
        essential: 'Niezbędny',
        functional: 'Funkcjonalny',
        necessary: 'Niezbędny',
        session: 'Sesja',
        persistent: 'Uporczywy',
        performance: 'Wydajność',
        analytics: 'Analityka',
        targeting: 'Kierowanie',
        advertising: 'Reklama',
        legal: 'Prawny',
        other: 'Inny',
        total_third_party_cookies: 'Całkowita liczba plików cookie stron trzecich',
        third_party_requests: 'Żądania stron trzecich',
        first_party_cookies: 'Pliki cookie pierwszej strony',
        cookie_policy_present: 'Obecna polityka plików cookie',
        privacy_policy_present: 'Obecna polityka priwatności',
        online_app_tool_used: 'Użyte narzędzia online',
        website_name: 'Nazwa strony',
        date_of_visit: 'Data odwiedzenia strony'
    },
    // Romanian
    'ro': {
        essential: 'Esenţial',
        functional: 'Funcţional',
        necessary: 'Necesar',
        session: 'Sesiune',
        persistent: 'Persistent',
        performance: 'Performanţă',
        analytics: 'Analytics',
        targeting: 'Direcționare',
        advertising: 'Publicitate',
        legal: 'Legal',
        other: 'Alte',
        total_third_party_cookies: 'Total cookie-uri terță parte',
        third_party_requests: 'Cereri ale terților',
        first_party_cookies: 'Cookie-uri primare',
        cookie_policy_present: 'Politica de cookie-uri Prezenta',
        privacy_policy_present: 'Politica de confidențialitate prezentă',
        online_app_tool_used: 'Instrumentul aplicației online folosit',
        website_name: 'Numele website-ului',
        date_of_visit: 'Data accesării website-ului'
    },
    // CZech
    'cz': {
        essential: 'Nezbytný',
        functional: 'Funkční',
        necessary: 'Nezbytné',
        session: 'Zasedání',
        persistent: 'Vytrvalý',
        performance: 'Výkon',
        analytics: 'Analytics',
        targeting: 'Cílení',
        advertising: 'Reklamní',
        legal: 'Právní',
        other: 'jiný',
        total_third_party_cookies: 'Celkový počet souborů cookie třetích stran',
        third_party_requests: 'Požadavky třetích stran',
        first_party_cookies: 'Cookies první strany',
        cookie_policy_present: 'Současné zásady používání souborů cookie',
        privacy_policy_present: 'Současné zásady ochrany osobních údajů',
        online_app_tool_used: 'Použitý nástroj online aplikace',
        website_name: 'jméno stránky'
    },
    // Finish
    'fi': {
        essential: 'Olennaista',
        functional: 'Toimiva',
        necessary: 'Välttämätön',
        session: 'istunto',
        persistent: 'Pysyvä',
        performance: 'Esitys',
        analytics: 'Analytics',
        targeting: 'Kohdistus',
        advertising: 'Mainonta',
        legal: 'Laillinen',
        other: 'Muut',
        total_third_party_cookies: 'Kolmannen osapuolen evästeet yhteensä',
        third_party_requests: 'Kolmannen osapuolen pyynnöt',
        first_party_cookies: 'Ensimmäisen osapuolen evästeet',
        cookie_policy_present: 'Evästekäytäntö esillä',
        privacy_policy_present: 'Tietosuojakäytäntö läsnä',
        online_app_tool_used: 'Käytetty verkkosovellustyökalu',
        website_name: 'Sivuston nimi',
        date_of_visit: 'Vierailun päivämäärä'
    },
    // Italian
    'it': {
        essential: 'Essenziale',
        functional: 'Funzionale',
        necessary: 'Necessaria',
        session: 'Sessione',
        persistent: 'Persistente',
        performance: 'Prestazione',
        analytics: 'Analitica',
        targeting: 'Targeting',
        advertising: 'Pubblicità',
        legal: 'Legale',
        other: 'Altra',
        total_third_party_cookies: 'Totale cookie di terze parti',
        third_party_requests: 'Richieste di terze parti',
        first_party_cookies: 'Cookie di prima parte',
        cookie_policy_present: 'Cookie Policy Presente',
        privacy_policy_present: 'Informativa sulla privacy Presente',
        online_app_tool_used: 'Strumento app online utilizzato',
        website_name: 'Nome del sito',
        date_of_visit: 'Data della visita'
    },

    // Hebrew
    'he': {
        website_name: 'שם האתר',
        date_of_visit: 'תאריך הביקור באתר',
        total_third_party_cookies: 'סך כל עוגיות צד שלישי',
        third_party_requests: 'Αιτήματα τρίτων μερών σύμφωνα με το εργαλείο',
        first_party_cookies: 'עוגיות צד ראשון',
        cookie_policy_present: 'Ύπαρξη πολιτικής απορρήτου',
        privacy_policy_present: 'Ύπαρξη πολιτικής απορρήτου',
        online_app_tool_used: 'Χρησιμοποιήθηκε διαδικτυακό εργαλείο'
    }

}